name: Test APP

on: [pull_request]

env:
  IMAGE_TAG: nestjs-api

jobs: 
  test: 
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t $IMAGE_TAG --target=build ./
      - name: Prettier
        run: docker run $IMAGE_TAG sh -c 'npm run format'
      - name: Eslint
        run: docker run $IMAGE_TAG sh -c 'npm run lint'
      - name: Tests
        run: docker run $IMAGE_TAG sh -c 'npm run test'